# Generated by Django 4.2 on 2023-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comercio', '0004_cliente_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
